LOCAL_PATH := device/TIMKOO/Q5

# Architecture details
TARGET_ARCH := arm
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_CPU_VARIANT := cortex-a7

# Platform definitions
TARGET_BOARD_PLATFORM := mt6582
TARGET_BOOTLOADER_BOARD_NAME := mt6582

# Exact parameters extracted from your Timmkoo boot image
BOARD_KERNEL_BASE := 0x80008000
BOARD_RAMDISK_OFFSET := 0x04000000
BOARD_PAGE_SIZE := 2048
BOARD_KERNEL_CMDLINE := 

# Standard partition constraints for older MediaTek 6582 layouts
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 10485760
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1342177280
BOARD_USERDATAIMAGE_PARTITION_SIZE := 2147483648

# TWRP / Recovery Build Flags
RECOVERY_VARIANT := twrp
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_NO_SELECT_BUTTON := true